# Authorization: Bearer kienboec-mtcgToken



GET http://localhost:8000/ HTTP/1.1

### GET all users
GET http://localhost:8000/users HTTP/1.1

### GET User by Username
GET http://localhost:8000/users?Username=Minas HTTP/1.1

### Login User
POST http://localhost:8000/sessions HTTP/1.1
Content-Type: application/json

{
    "Username":"Minas",
    "Password":""
}

### Add User
POST http://localhost:8000/users HTTP/1.1
Content-Type: application/json

{
    "Username":"Test123443434343", 
    "Password":"Mina$2024"
}

### DELETE User
DELETE http://localhost:8000/users/Mina HTTP/1.1
Content-Type: application/json

