# Authorization: Bearer kienboec-mtcgToken



GET http://localhost:8000/ HTTP/1.1

### GET all users
GET http://localhost:8000/users HTTP/1.1

### GET User by Username
GET http://localhost:8000/users?Username=Vamos1 HTTP/1.1

### Login User
POST http://localhost:8000/sessions HTTP/1.1
Content-Type: application/json

{
    "Username":"Vamos",
    "Password":"Test1"
}

### Add User
POST http://localhost:8000/users HTTP/1.1
Content-Type: application/json

{
    "Username":"Vamos", 
    "Password":"Test1"
}

### DELETE User
DELETE http://localhost:8000/users/Vamos HTTP/1.1
Content-Type: application/json

### UPDATE User
PATCH http://localhost:8000/users/Vamos HTTP/1.1
Content-Type: application/json

{
    "Username": "Vamos1",
    "dsadas": 3000
}

