# Authorization: Bearer kienboec-mtcgToken

GET http://localhost:8000/ HTTP/1.1

### GET all users
GET http://localhost:8000/users HTTP/1.1

### GET User by Username
GET http://localhost:8000/users/RoleTest HTTP/1.1
Authorization: Bearer RoleTest-a185babc-3744-4edf-aa26-11d31bb2fedf

### Register User
POST http://localhost:8000/users HTTP/1.1
Content-Type: application/json

{
    "Username":"RoleTest", 
    "Password":"Test1",
    "Role": "user"
}

### Register Admin
POST http://localhost:8000/users HTTP/1.1
Content-Type: application/json

{
    "Username":"Mina", 
    "Password":"Admin123",
    "Role": "admin"
}

### Login User
POST http://localhost:8000/sessions HTTP/1.1
Content-Type: application/json

{
    "Username":"RoleTest",
    "Password":"Test1"
}

### Login Admin
POST http://localhost:8000/sessions HTTP/1.1
Content-Type: application/json

{
    "Username":"Mina",
    "Password":"Admin123"
}

### DELETE User
DELETE http://localhost:8000/users/RoleTest HTTP/1.1
Content-Type: application/json

### UPDATE User
PUT http://localhost:8000/users/RoleTest HTTP/1.1
Content-Type: application/json
Authorization: Bearer RoleTest-8debc67f-ba5b-4528-a34e-65730bced300

{
    "Username": "RoleTest",
    "Elo": 3000
}

### Create Package
POST http://localhost:8000/packages HTTP/1.1
Content-Type: application/json
Authorization: Bearer admin-054ba651-e1f1-4c59-bd7f-7356571e8c77

[
  {
    "Id": "845f0dc7-37d0-426e-994e-43fc3ac83c08", 
    "Name": "WaterGoblin", 
    "Damage": 10
  }, 
  {
    "Id": "99f8f8dc-e25e-4a95-aa2c-782823f36e2a", 
    "Name": "Dragon", 
    "Damage": 50
  }, 
  {
    "Id": "e85e3976-7c86-4d06-9a80-641c2019a79f",
    "Name": "WaterSpell",
    "Damage": 20
  }, 
  {
    "Id": "1cb6ab86-bdb2-47e5-b6e4-68c5ab389334", 
    "Name": "Ork", 
    "Damage": 45
  }, 
  {
    "Id": "dfdd758f-649c-40f9-ba3a-8657f4b3439f", 
    "Name": "FireSpell",    
    "Damage": 25
  }
]

### GET Packages
GET http://localhost:8000/packages HTTP/1.1

### GET Package by ID
GET http://localhost:8000/packages?Id= HTTP/1.1

### Acquire Package
POST http://localhost:8000/transactions/packages
Content-Type: application/json
Authorization: Bearer RoleTest-8debc67f-ba5b-4528-a34e-65730bced300